# Site settings
title: A.J. Fillo
email: filloa@oregonstate.edu
url: https://aaronfillo.github.io
description: "Personal site for A.J. Fillo, Oregon State University Ph.D. Candidate, Mechanical Engineer, and Host of Lib Lab on YouTube"
skills: "Mechanical Engineer - Researcher - Educator"
meta_author: Fillo Aaron
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: A.J. Fillo

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 28283c #18bc9c #80B3FF
  primary-rgb: "40,40,60" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Aaron Fillo
  location: Corvallis, OR
  social: # @MostlyEnginerd
  credits: Designed and built by A.J. Fillo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MostlyEnginerd
  - title: instagram
    url: http://instidy.com/mostlyenginerd
  - title: linkedin
    url: https://www.linkedin.com/in/aaron-fillo-63789b94/
  - title: github
    url: https://github.com/aaronfillo

# Postal address (add as many lines as necessary)
address:
  - line: 204 Rogers Hall
  - line: Oregon State Univeristy
  - line: Corvallis, OR 97331

# Credits content
credits: 'This site is based on Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
